#define LEXICAL_ERROR 1
#define SYNTAX_ERROR 2
#define SEM_UNDECL_VAR_ERROR 3
#define SEM_ARGS_ERROR 4
#define SEMANTIC_ERROR 6
#define COMPL_ERROR 99
#define WRONG_PARAMS_ERROR 50

#define IFJ_ANALYZE_ERROR 51
#define IFJ_SEMANTIC_ERROR 52
#define IFJ_OP_TYPE_ERROR 53
#define IFJ_UNEXIST_VAR_ERROR 54
#define IFJ_UNEXIST_VAL_ERROR 56
#define IFJ_DIV_BY_ZERO 57
#define IFJ_STR_ERROR 58
#define IFJ_DEFAULT_ERROR 60
